Orckestra/orc-shared

docs/components.md, docs/lists.md, src/components/CategoryList.js, src/components/CategoryList.test.js, src/components/List/List.js, src/components/List/withListState.js
Adds a CategoryList component which shows rows as members of closable groups.
=> Category list

.travis.yml, src/components/Form/Form.js, src/components/Form/Inputs/Date.js, src/components/Form/Inputs/Date.test.js
Change the built-in date input to a constructed input set which has better UX and design.
=> Better date input

docs/components.md, package.json, src/components/AppFrame/Topbar.js, src/components/DropMenu/DropMenu.test.js, src/components/DropMenu/Menu.js, src/components/DropMenu/Menu.test.js, src/components/DropMenu/index.js, src/components/Navigation/Bar.js, src/components/Navigation/Bar.test.js, src/components/Navigation/Navigation.test.js, src/components/Navigation/Tab.js, src/components/Navigation/useNavigationState.js, src/components/Navigation/useNavigationState.test.js, src/components/Scope/index.js
Navigation tabs respond to available screen width by showing a dropdown and scrolling to the active tab.
=> Fixes 36350: Better navigation tabs

src/actions/authentication.js, src/actions/authentication.test.js, src/buildStore.js
Set the return url upon signing out.
=> Added the return url upon Signing Out

src/actions/authentication.test.js, src/buildStore.js, src/components/DropMenu/DropMenu.test.js, src/components/List/Row.js
window.location.origin was not working as expected unfortunately. I had to use window.BASE_PATH in my function instead of "basename" because otherwise, I would not be able to unit tests the sign-out properly.
=> Sign in back was not working correctly with the return URL.

docs/infrastructure.md, src/actions/versionInfo.js, src/actions/versionInfo.test.js, src/buildStore.js, src/buildStore.test.js, src/components/AppFrame/About.js, src/components/AppFrame/About.test.js, src/components/AppFrame/AppFrame.js, src/components/AppFrame/AppFrame.test.js, src/components/AppFrame/Help.js, src/components/AppFrame/Help.test.js, src/components/AppFrame/Topbar.js, src/components/AppFrame/Topbar.test.js, src/components/AppFrame/useApplicationHelpUrl.js, src/components/AppFrame/useApplicationHelpUrl.test.js, src/components/AppFrame/useVersionInfo.js, src/components/AppFrame/useVersionInfo.test.js, src/components/DropMenu/DropMenu.test.js, src/components/List/Row.js, src/reducers/versionInfo.js, src/reducers/versionInfo.test.js, src/selectors/versionInfo.js, src/selectors/versionInfo.test.js, src/utils/buildUrl.js, src/utils/buildUrl.test.js
- Added the Help button at the top-right corner of the shell
- Added the call the a new request in order to fetch the version and Help URLs (OcrkestraCommerce PR is still pending, should be reviewed by Benoit tuesday)
- Both OMS and Analytics will need to be changed in order to:
1- Add the localisations of the Help button
2- The new Prop when using AppFrame
3- The call to the new action "getVersionInfo()" in index.js
=> Added the required Help button at the top-right corner

docs/components.md, src/components/ColumnWrapper.js, src/components/ColumnWrapper.test.js
Add common column wrapper for column definitions for use by apps.
Documentation added as well.
=> Add common column wrapper for column definitions for use by apps

src/components/AppFrame/AppFrame.js, src/components/AppFrame/AppFrame.test.js
=> AppFrame is pushed out of visible view port when opening side bar menu.

package.json, src/components/Scope/ScopeNode.js, src/components/Treeview/Label.js
All is in the title.
Story: #36927
=> Fixed wordwrap of scopes in the selector for IE

src/components/Modules.test.js, src/components/Navigation/Bar.js, src/components/Navigation/Bar.test.js, src/components/Navigation/Tab.js, src/components/Navigation/Tab.test.js, src/components/Navigation/useNavigationState.js, src/components/Navigation/useNavigationState.test.js, src/components/Text.js, src/components/Text.test.js, src/hooks/useLabelMessage.js, src/hooks/useLabelMessage.test.js
=> Modified tab compoenent to handle truncation of order tabs.

src/components/AppFrame/About.js, src/components/AppFrame/Help.js, src/components/AppFrame/Help.test.js
=> Web site should open in a new tab.

src/actions/versionInfo.js, src/actions/versionInfo.test.js, src/buildStore.js, src/components/AppFrame/AppFrame.js, src/components/AppFrame/Help.test.js, src/reducers/localeFactory.js, src/selectors/locale.js
=> Help should open in English when any other languages than French.

src/components/AppFrame/MenuItem.js, src/components/Modules.test.js, src/components/Navigation/Bar.js, src/components/Navigation/Navigation.test.js, src/components/Navigation/Tab.js, src/components/Navigation/Tab.test.js, src/components/Navigation/useNavigationState.js, src/components/Navigation/useNavigationState.test.js, src/reducers/navigation.js, src/reducers/navigation.test.js, src/schemas/scopes.js, src/selectors/navigation.js, src/selectors/navigation.test.js
=> Changing scope duplicates order tabs

package.json, src/components/List/DataCell.test.js, src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js, src/components/MaterialUI/Inputs/SelectProps.js, src/components/MaterialUI/Inputs/SelectProps.test.js, src/components/MaterialUI/muiThemes.js, src/components/MaterialUI/muiThemes.test.js, src/components/Selector.js, src/selectors/navigation.js, src/utils/localizationHelper.js, src/utils/localizationHelper.test.js, src/utils/propertyHelper.js, src/utils/propertyHelper.test.js
Story: #36654
- Created Select Wrapper from the Material-UI
- Created muiThemes helper file so common themes for all applications (OMS, Analytics, future ones) will be in one place one
- Added helper functions for localization
=> Added Select Wrapper component from Material-UI and localization helper functions

src/components/MaterialUI/Inputs/Checkbox.js, src/components/MaterialUI/Inputs/Checkbox.test.js, src/components/MaterialUI/Inputs/CheckboxProps.js, src/components/MaterialUI/Inputs/CheckboxProps.test.js, src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js, src/components/MaterialUI/Inputs/SelectProps.test.js, src/components/MaterialUI/Surfaces/ExpansionPanel.js, src/components/MaterialUI/muiThemes.js
=> Added a Checkbox wrapper for flagged orders story

src/actions/versionInfo.js, src/actions/versionInfo.test.js, src/components/AppFrame/AppFrame.js, src/components/Toolbar.js
=> Toolbar does not resize correctly when needed

src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/Table.test.js, src/components/MaterialUI/DataDisplay/Tooltip.js, src/components/MaterialUI/Placeholder.js, src/components/MaterialUI/Placeholder.test.js
added Placeholder component and added ability to use placeholder in MaterialUI Table
=> Show empty list icon

src/components/MaterialUI/DataDisplay/tableHelpers.js, src/components/MaterialUI/DataDisplay/tableHelpers.test.js, src/hooks/useViewState.js, src/hooks/useViewState.test.js
=> Added a function to reset view state when required

src/components/MaterialUI/Inputs/Radio.js, src/components/MaterialUI/Inputs/Radio.test.js, src/components/MaterialUI/Inputs/RadioProps.js, src/components/MaterialUI/Inputs/RadioProps.test.js, src/components/Toolbar.js, src/components/Toolbar.test.js
Add Radio component
Add ratio tool to ToolBar
=> Add Radio component

src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js, src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js, src/components/MaterialUI/Inputs/SelectProps.js, src/components/MaterialUI/Inputs/SelectProps.test.js
=> Select drop down should be aligned on the left side

src/components/MaterialUI/Inputs/TimePicker.js, src/components/MaterialUI/Inputs/TimePicker.test.js
=> Correct TimePicker set hour issue for IE

src/components/MultiSelector.js, src/components/Selector.js
The MultiSelector was not showing the dropdown list properly.
The max width for Selector and MultiSelector was not set.
=> Corrected MultiSelector component which was not showing options

src/components/MaterialUI/DataDisplay/PredefinedElements/TableInfoBar.js, src/components/MaterialUI/DataDisplay/PredefinedElements/TableInfoBar.test.js, src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/Table.test.js, src/components/MaterialUI/Inputs/TimePicker.js, src/components/Navigation/Bar.js, src/components/Navigation/Tab.js
Add tableInfo property to Table and new TableInfoBar component
=> Add tableInfo property to Table and TableInfoBar component

src/components/MaterialUI/DataDisplay/Notification.js, src/components/MaterialUI/DataDisplay/Notification.test.js, src/components/MaterialUI/DataDisplay/NotificationProps.js, src/components/MaterialUI/DataDisplay/NotificationProps.test.js, src/components/MaterialUI/DataDisplay/index.js
[AB#41152](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/41152)
=> add notification component

src/components/AppFrame/Sidebar.js, src/components/AppFrame/Sidebar.test.js
[AB#42540](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42540) - show title on hover for sidebar icons
=> Show title on hover for sidebar icons

src/utils/propertyHelper.js, src/utils/propertyHelper.test.js
[AB#42855](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42855)
=> fix helper

src/selectors/view.js
[AB#43106](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43106)
=> edit mode fix

src/components/Modules.js, src/components/Modules.test.js, src/selectors/scope.js, src/selectors/scope.test.js
[AB#42568](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42568)
=> redirect authorized scope

src/components/MaterialUI/DataDisplay/PredefinedElements/InformationItem.js
[AB#43296](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43296)
=> Fix color for required asterix

src/components/MaterialUI/Navigation/TabBar.js, src/components/Routing/SegmentPage.js
[AB#43281](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43281)
=> Fix style for modified Tab and section

src/components/Modules.js, src/components/Modules.test.js
[AB#42568](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42568)
=> fix redirect to valid scope

package.json, src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/tableHelpers.js, src/components/MaterialUI/DataDisplay/tableHelpers.test.js, src/components/MaterialUI/Inputs/Checkbox.js, src/components/MaterialUI/Inputs/Switch.js, src/components/MaterialUI/Inputs/Switch.test.js, src/components/MaterialUI/Inputs/SwitchProps.js, src/components/MaterialUI/Inputs/SwitchProps.test.js
updated table, change switch in tableHelpers to MaterialUI component, updated Checkbox and Switch components to current needs [AB#40712](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/40712), [AB#40288](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/40288)
=> US #40712, #40288 - schedule and schedule exceptions 

package.json, src/components/MaterialUI/DataDisplay/PredefinedElements/Placeholder.js, src/components/MaterialUI/DataDisplay/PredefinedElements/Placeholder.test.js
This is related to https://dev.azure.com/orckestra001/OrckestraCommerce/_workitems/edit/43362/
=> Extend placeholder for tables

src/components/MaterialUI/Inputs/Radio.js, src/components/MaterialUI/Inputs/Switch.js
[AB#42212](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42212)
=> Fix default value check

src/components/MaterialUI/Inputs/Select.js
https://dev.azure.com/orckestra001/OrckestraCommerce/_workitems/edit/39979/
=> Fix label style for Select component

src/sharedMessages.js
[AB#43637](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43637)
=> fix translation string ids

package.json, src/actions/applications.js, src/actions/authentication.js, src/actions/countries.js, src/actions/locale.js, src/actions/requestsApi.js, src/actions/scopes.js, src/actions/timezones.js, src/actions/versionInfo.js
=> Use generated API instead of buildUrl

.gitignore, src/components/MaterialUI/DataDisplay/TooltippedElements/TooltippedIcon.js, src/components/MaterialUI/DataDisplay/TooltippedElements/TooltippedIcon.test.js
=> Icon with tooltip

src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/Table.test.js, src/components/MaterialUI/DataDisplay/TableProps.js, src/components/MaterialUI/DataDisplay/TableProps.test.js, src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/Inputs/Select.js
[AB#43803](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43803)
=> updated table component

src/components/MaterialUI/DataDisplay/TooltippedElements/TooltippedTypography.js, src/components/MaterialUI/Navigation/TabBar.js, src/components/MaterialUI/Navigation/TabLabel.js, src/components/MaterialUI/Navigation/TabLabel.test.js, src/components/MaterialUI/ScopeSelector/TreeView.js, src/components/MaterialUI/ScopeSelector/TreeView.test.js
[AB#42991](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42991)
=> Fix bug with long name for Tabs - use TooltippedTypography

src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.js, src/sharedMessages.js, src/translations/en-US.json, src/translations/fr-CA.json, src/translations/it-IT.json
[AB#42211](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42211)
=> Fix default Confirm Button title for Modal Stepper. Should be Apply Changes

src/components/MaterialUI/DataDisplay/TooltippedElements/TooltippedIcon.js, src/components/MaterialUI/DataDisplay/TooltippedElements/TooltippedIcon.test.js
=> Add className to TooltippedIcon

src/components/MaterialUI/DataDisplay/Modal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.test.js, src/components/MaterialUI/DataDisplay/TransferList.js
@a-rousseau please review the common style for Modal Title. Right now we duplicate everywhere styles for title, let define some common one
=> Common styles for Modal Title:

src/components/MaterialUI/DataDisplay/TransferList.js, src/components/MaterialUI/DataDisplay/TransferList.test.js
[AB#41026](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/41026)
[AB#40770](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/40770)
=> Add Lazy Load to Transfer List

src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js
[AB#41117](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/41117)
=> fix select default value

src/utils/mapHelper.js, src/utils/mapHelper.test.js
[AB#41117](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/41117)
=> add able map model with nested fields

src/components/MaterialUI/DataDisplay/List.js, src/components/MaterialUI/DataDisplay/List.test.js, src/components/MaterialUI/DataDisplay/TransferList.js
Add List component with Single select and with scrollLoadee event
=> List component with scroll loader

src/selectors/navigation.js
[AB#44295](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/44295)
=> add is slash exist check

src/components/AppFrame/MenuItem.js, src/components/AppFrame/MenuItem.test.js
Add ability to a hide menu item
=> Add ability to a hide menu item

src/actions/view.js, src/actions/view.test.js, src/components/MaterialUI/Feedback/useNotification.js, src/hooks/useMultipleFieldEditState.js, src/hooks/useMultipleFieldEditState.test.js, src/reducers/view.js, src/reducers/view.test.js
=> Add multiple fields edit state

src/utils/modelValidationHelper.js, src/utils/modelValidationHelper.test.js
=> Add new multiple field validation helper

src/components/MaterialUI/Navigation/TabBar.js
[AB#43882](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43882)
=> FIx style for Tab with modifications

src/components/MaterialUI/DataDisplay/TimelineItem.js, src/components/MaterialUI/DataDisplay/TimelineItem.test.js
Missing the connector between items
=> Add TimelineConnector

.az.yml, package.json, src/components/MaterialUI/DataDisplay/List.js, src/components/MaterialUI/DataDisplay/Modal.js, src/components/MaterialUI/Feedback/useNotification.test.js, src/components/Navigation/useNavigationState.js, src/hooks/useEditState.js, src/hooks/useMultipleFieldEditState.test.js, src/utils/mapHelper.js, src/utils/urlHelper.js
=> Enforce linter during build and validate translation during pre-commit hook

src/components/MaterialUI/Feedback/NotificationContext.js, src/components/MaterialUI/Feedback/NotificationContext.test.js, src/components/MaterialUI/Feedback/useNotification.js, src/components/MaterialUI/Feedback/useNotification.test.js, src/constants.js, src/utils/requestProcessingHelper.js, src/utils/requestProcessingHelper.test.js
Notification context allows to wrap the app component in NotificationContextProvider and then access addNotification function through the NotificationContext. So, it makes notifications global and it won't be necessary to care anymore about component for notification. All what you need to do is just add new notification from anywhere and it will work!
RequestProcessingHelper exposes computeFinalRequestProcessingState which computes the final states depends on passed states. Using this function it will be possible to determine the global state of your "business action" which could contain multiple "http requests". 
It will be helpful also in context of **chain of request** which highly likely will be built in the future.
=> Implement notification context and request processing engine

src/components/MaterialUI/muiThemes.js
Add default styling for Material UI's Timeline component
=> Add default Timeline styling

src/components/MaterialUI/Inputs/InputBase.js, src/components/MaterialUI/Inputs/InputBaseProps.js, src/components/MaterialUI/Inputs/InputBaseProps.test.js
=> Added styling rules on errorText for the InputBase

src/components/MaterialUI/Inputs/InputBase.js, src/components/MaterialUI/Inputs/InputBase.test.js, src/components/MaterialUI/Inputs/InputBaseProps.js, src/components/MaterialUI/Inputs/InputBaseProps.test.js, src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js, src/components/MaterialUI/Inputs/SelectProps.js, src/components/MaterialUI/Inputs/SelectProps.test.js
Add start and end adornment props to InputBase
Add error display to Select
=> add some input props

src/components/MaterialUI/DataDisplay/Modal.js, src/components/MaterialUI/muiThemes.js
+ Add Outline variant styling for IconButton
+ Add Contained variant styling for IconButton
+ Set a fixed max-height for Wide Modal
+ Fixed calculated height to be applied on the height of the Wide Modal
=> Iconbutton and Modal adjustments

src/selectors/authentication.js, src/selectors/authentication.test.js
Add permissions for Reader on order
=> Add Reader permissions

src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.test.js, src/components/MaterialUI/muiThemes.js
Fixed icon sizes in MuiButton
Fixed icons sizes in MuiIconButton
Add a primary outline style to MuiIconButton
=> Fix icon size in buttons

src/components/MaterialUI/DataDisplay/Icon.js, src/components/MaterialUI/muiThemes.js
Move Icon Wrapper styling definitions to the Theme definition
=> Fix Icon wrapper to be styled properly

src/components/MaterialUI/muiThemes.js, src/components/Routing/SegmentPage.js
+ Add css pointer cursor for SegmentPage Items
+ Fix base icon color
=> Add pointer cursor on MouseOver for SegmentPage Items

src/hooks/useViewState.js
This will allow the return values to be used with useEffect
#41583
=> Add useCallback to useViewState

src/hooks/useEditState.js, src/hooks/useEditState.test.js
added getValidPath function to get proper path if there any "value" props inside
=> added getValidPath function

src/components/AppFrame/AppFrame.test.js, src/components/Scope/Scope.test.js, src/components/Scope/useScopeData.test.js, src/hocs/withScopeData.test.js, src/selectors/scope.js, src/selectors/scope.test.js, src/utils/index.js
Refactor selectLocalizedScopes
[AB#45602](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/45602)
=> Use Scope Id when displayName is absent

src/components/MaterialUI/DataDisplay/Modal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.js
Added the event object for click event from Modal implementation
so we can prevent propagation in custom handler.
Story: #41912
=> Added the event object for click event from Modal implementation

src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/Table.test.js, src/components/MaterialUI/DataDisplay/TableProps.js, src/components/MaterialUI/DataDisplay/TableProps.test.js, src/components/MaterialUI/DataDisplay/tableHelpers.js, src/components/MaterialUI/DataDisplay/tableHelpers.test.js, src/components/MaterialUI/DataDisplay/useTableSelection.js, src/components/MaterialUI/DataDisplay/useTableSelection.test.js
Adjusted table row selection handlers so it can be controlled
from the component using the table.
Story: #43105
=> Adjusted table row selection handlers

src/actions/view.js, src/hooks/useEditState.js, src/hooks/useEditState.test.js, src/reducers/view.js, src/reducers/view.test.js
added ability to remove items by path in dynamic edit state and remove errors in validation
=> added ability to remove items by path in dynamic edit state

src/components/MaterialUI/Inputs/Radio.js, src/components/MaterialUI/muiThemes.js
+ Fixed MuiIconButton styling for outlined, contained and default
+ Added white background color to Radio buttons
=> Fix Radio and IconButton styling

src/components/MaterialUI/DataDisplay/PredefinedElements/SectionTitle.js, src/components/MaterialUI/DataDisplay/PredefinedElements/SectionTitle.test.js, src/components/MaterialUI/muiThemes.js
+ Allow TitledPapers to have no Title rendered if null
+ Create more complete styling for IconButtons
=> IconButton and TitledPaper update

src/components/MaterialUI/DataDisplay/PredefinedElements/SectionTitle.js
Component needs to return a value even if null
=> Fix error in SectionTitle

src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js
[AB#45337](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/45337)
=> fix style for disabled select

src/components/AppFrame/MenuItem.js, src/components/MaterialUI/DataDisplay/PredefinedElements/ActionModal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/ActionModal.test.js, src/components/Navigation/useNavigationState.js, src/components/Navigation/useNavigationState.test.js
=> Added the possibility to configure closing tab handler

src/components/MaterialUI/DataDisplay/TransferList.js, src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/Inputs/DatePicker.test.js, src/components/MaterialUI/muiThemes.js
- Replaced deprecated Icon call with the correct one
- Modified Typography component in List for Transferlist to render as span
+ Fixed padding in History list
=> Fix warnings in OMS

src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.test.js
Add a new type option for StepperModal component
- Default will ne wide
- Allows normal, wide and fullwidth when using Modal component
Story ABCD#44268
=> Add StepperModal type option (to allow wide)

src/components/MaterialUI/Surfaces/ExpansionPanel.js, src/components/MaterialUI/Surfaces/expansionPanelProps.js, src/components/MaterialUI/Surfaces/expansionPanelProps.test.js
+ Add props for styling for ExpansionPanel Summary root and expanded styles
+ Add props for styling ExpansionPanel details
+ Add props for styling ExpansionPanel actions
+ Implement styling to the proper parts of the component
=> Add props to ExpansionPanel for styling flexibility

src/components/MaterialUI/DataDisplay/TransferList.js, src/components/MaterialUI/DataDisplay/TransferList.test.js
- Removed unnecessary styling on grid container
- Removed superfluous div
=> Fix styling and layout

src/components/MaterialUI/DataDisplay/TransferList.js, src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js
Changed Typography to be rendered as Span for ListItem title
=> Fix Dom error warnigns

src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/DataDisplay/Table.test.js, src/components/MaterialUI/DataDisplay/useTableSelection.js
Clearing checkboxes selection outside the Table component was not working properly.
Story: #47007
=> Clearing checkboxes selection outside the Table component was not working properly.

src/components/MaterialUI/DataDisplay/SelectionList.js, src/components/MaterialUI/DataDisplay/SelectionList.test.js
The SelectionList component will now put a divider property if it has any contents.
Story ABCD#44271
=> Add divider to left of info panel for SelectionList

src/selectors/view.js, src/selectors/view.test.js
Allows us to highlight instances with error
[AB#46813](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/46813)
=> Get instances with errors by path

src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/Inputs/Select.test.js
+ Add the ability to read the disabled property if set
+ Add the ability to read the isGroupHeader property if set
+ Change rendering accordingly
+ Fix Unit tests
=> Add the ability to set a select option as a group header or disabled

src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js
=> Prevent event when enter key is pressed in SearchControl

src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.js, src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.test.js
- Allow StepperModal step to disable Next with function
- step now allows a function to be passed to nextDisabled
Story ABCD#44358
=> Allow StepperModal step to disable Next with function

src/utils/localizationHelper.js, src/utils/localizationHelper.test.js
=> Change how empty values are handled by getLocalization

src/components/MultiSelector.js
=> Fix MultiSelector overflow

src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/muiThemes.js, src/components/Routing/SegmentPage.js, src/components/Routing/SegmentPage.test.js
+ Update Select component max width styling
+ Prevent wrapping on SegmentPage items for proper alignment
+ Update all disabled Buttons styling
=> Styles update

src/components/MaterialUI/DataDisplay/Modal.js
Replaced minWidth with simply width
=> Update fullwidth definition

src/components/MaterialUI/Inputs/Select.js
Removed the fixed width and made it automatic
=> Fix width and min-width for Select Dropdown

src/components/MaterialUI/DataDisplay/List.js
[AB#48553](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/48553)
=> fix item compare

src/components/MaterialUI/Inputs/InputBase.js, src/components/MaterialUI/Inputs/InputBase.test.js, src/components/MaterialUI/Inputs/InputBaseProps.js, src/components/MaterialUI/Inputs/InputBaseProps.test.js
- Allow autoComplete for InputBase to be set
Story #48413
=> Allow autoComplete for InputBase to be set

src/components/MaterialUI/Inputs/InputBase.js, src/components/MaterialUI/Inputs/InputBase.test.js
=> Add InputBase test for autoComplete with a value

src/components/MaterialUI/DataDisplay/TransferList.js
[AB#48553](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/48553)
=> fix compare items

src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js, src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.test.js
[AB#48186](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/48186)
=> focus on input when click clear button

src/selectors/scope.js, src/selectors/scope.test.js
=> Add Scope Default Culture selector

src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/Inputs/DatePicker.test.js
[AB#46516](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/46516)
=> implemented localization of DatePicker US#46516

src/components/MaterialUI/DataDisplay/TableHeaderCell.js, src/components/MaterialUI/DataDisplay/TableHeaderCell.test.js
[AB#47869](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/47869)
=> fixed arrow in table headers #47869

src/components/MaterialUI/Inputs/Autocomplete.js, src/components/MaterialUI/Inputs/Autocomplete.test.js
[AB#44323](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/44323)
=> fixed input id

src/components/MaterialUI/Inputs/Autocomplete.js, src/components/MaterialUI/Inputs/Autocomplete.test.js, src/components/MaterialUI/Inputs/AutocompleteProps.js, src/components/MaterialUI/Inputs/AutocompleteProps.test.js
[AB#49231](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/49231)
=> add clear icon

src/components/MaterialUI/Inputs/Radio.js
=> Fix to alignment issue and missing class

src/components/MaterialUI/Inputs/Autocomplete.js
[AB#49640](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/49640)
=> fix height

src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js, src/components/MaterialUI/Inputs/Select.js, src/components/MaterialUI/ScopeSelector/TreeItem.js, src/components/MaterialUI/ScopeSelector/TreeItem.test.js, src/components/MaterialUI/muiThemes.js
Fix TreeView to have proper styling with correct line ending
Fix Select component to have proper styling when focused
Fix Select component inside SearchControl to have proper styling when focused
Fix Select component to have proper styling when disabled
Fix Select component when displaying icon only button with proper styling
Add italic styling for empty options in Select component
=> TreeView and Select component fixes

src/hooks/useEditState.js, src/hooks/useEditState.test.js
js forEach is not interrupted by return, using for instead
=> fix an editState validation bug

src/actions/metadata.js, src/actions/metadata.test.js, src/actions/requestsApi.js, src/constants.js, src/reducers/metadata.js, src/reducers/metadata.test.js, src/schemas/definitions.js, src/schemas/metadata.js, src/schemas/productDefinitions.js, src/selectors/metadata.js, src/selectors/metadata.test.js
metadata were transferred from OMS to be reusable. I took a full files from OMS. If there is something that is related only to OMS and will never be reused please let me know
=> transfer metadata from OMS to orc-shared

src/selectors/metadata.js
[AB#43317](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43317)
=> export mappedDefinitionEntity

src/reducers/metadata.js, src/selectors/metadata.js
[AB#44657](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/44657)
=> export definition

src/selectors/metadata.js, src/selectors/metadata.test.js, src/sharedMessages.js, src/translations/en-US.json, src/translations/fr-CA.json
[AB#44658](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/44658)
=> add definitionBuiltInAttributesSelector

src/actions/metadata.js, src/actions/metadata.test.js, src/actions/requestsApi.js, src/reducers/metadata.js, src/reducers/metadata.test.js, src/selectors/metadata.js, src/selectors/metadata.test.js
=> Added calls to customer lookup update APIs

src/actions/metadata.js, src/actions/metadata.test.js, src/components/MaterialUI/Navigation/TabBar.js, src/components/MaterialUI/Navigation/TabBar.test.js, src/components/Navigation/useNavigationState.js, src/components/Routing/FullPage.js, src/components/Routing/FullPage.test.js, src/components/Routing/Segment.js, src/components/Routing/Segment.test.js, src/components/Routing/SegmentPage.js, src/components/Routing/withWaypointing.js, src/components/Routing/withWaypointing.test.js, src/constants.js, src/hooks/useNotificationRequestState.js, src/hooks/useNotificationRequestState.test.js, src/hooks/useRequestState.js, src/hooks/useRequestState.test.js, src/reducers/metadata.js, src/reducers/metadata.test.js, src/reducers/requestStates.js, src/reducers/requestStates.test.js, src/selectors/metadata.js, src/selectors/metadata.test.js, src/sharedMessages.js, src/translations/en-US.json, src/translations/fr-CA.json
- Added necessary request in metadata actions to creare lookups
- Added the capabililty to set custom props to Components
- Added "creates" request state
- Added the possibility to receive the error message in the errorAction of useNotificationRequestState
Story: #50402, #50431
=> Added capability to add lookups in the OMS

src/components/MaterialUI/muiThemes.js
+ Added line masking when we have chevrons in the tree view to add some visual padding
- added styling to hide empty MuiTreeItem-iconContainer (chevrons)
=> Update Theme for MuiTreeView

src/components/MaterialUI/DataDisplay/SelectionList.js, src/components/MaterialUI/DataDisplay/SelectionList.test.js
=> Allow SelectionList to use all the space available

src/actions/metadata.js, src/actions/metadata.test.js, src/actions/requestsApi.js, src/reducers/metadata.js, src/reducers/metadata.test.js, src/selectors/metadata.js, src/selectors/metadata.test.js
[AB#44657](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/44657)
=> implement lookup saveRequestState in profile definition

src/actions/metadata.js, src/actions/metadata.test.js, src/reducers/metadata.js, src/reducers/metadata.test.js
[AB#51189](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/51189)
=> fix update profile definition request

src/utils/setTranslationWithFallback.js, src/utils/setTranslationWithFallback.test.js
[AB#51489](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/51489)
=> fix translate

package.json, src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/muiThemes.js
=> Add styles to the datepicker

src/components/MaterialUI/ScopeSelector/ScopeSelector.js, src/components/Sidepanel.js, src/components/Sidepanel.test.js
+ Gave the ScopeSelector a fixed width of 500px (31.25rem)
+ Removed width attribute on the scope selector
=> Fix ScopeSelector Width Error

src/components/MaterialUI/DataDisplay/TransferList.js
[AB#52563](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/52563)
Change the background color of the line masks to match the container background color
=> Fix Scope Selector display in Transfer List

src/components/MaterialUI/DataDisplay/Table.js, src/components/MaterialUI/muiThemes.js
[AB#49381](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/49381)
Added min width for tables
Reduced left and right padding for table cells
Added min width for SectionExpansionPanel (Accordion)
Added auto scroll on SectionExpansionPanel (Accordion)
=> Fix Resize on Smaller screen for Tables and SectionExpansionPanel

src/components/MaterialUI/DataDisplay/SelectionList.js, src/components/MaterialUI/DataDisplay/SelectionList.test.js
This reverts commit 876605129ab601fb48fa9b8b94f0bf0e6bf44245.
=> Revert "Rename object parameter to its expected value "left""

LICENSE, README.md, src/components/AppFrame/About.js, src/translations/en-US.json, src/translations/fr-CA.json
=> Make copyright year dynamic

src/components/MaterialUI/DataDisplay/PredefinedElements/Translations.test.js, src/components/MaterialUI/Inputs/InputBase.js, src/components/MaterialUI/Inputs/InputBase.test.js, src/components/Scope/Scope.test.js
Improve performance when typing in an input component by adding a delay to the update.
#50267
=> Improve performance when typing

src/components/AppFrame/AppFrame.js, src/components/AppFrame/AppFrame.test.js, src/components/AppFrame/MenuItem.js, src/components/Routing/FullPage.js, src/components/Routing/FullPage.test.js
Story: [AB#54489](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/54489)
=> Introduce the concept of custom "routerComponent"

src/components/Routing/SubPage.js, src/components/Routing/SubPage.test.js
Render buttons received from props if any. Render a single close button otherwise
=> SubPage - Render buttons passed from props instead of existing ones, if any

src/components/Form/InputField.test.js, src/components/Form/Inputs/Date.test.js, src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/Inputs/DatePicker.test.js, src/components/MaterialUI/Inputs/TimePicker.test.js, src/utils/timezoneHelper.js, src/utils/timezoneHelper.test.js
[AB#59428](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/59428)
=> fixed date time zone

src/components/MaterialUI/Inputs/DatePicker.js, src/components/MaterialUI/Inputs/DatePicker.test.js
[AB#59428](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/59428)
=> added useTimeZone to datePicker

src/utils/timezoneHelper.test.js
[AB#59428](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/59428)
=> fixed time zone helper test
