Orckestra/orc-shared

docs/forms.md
src/components/Form/FieldElements.js
src/components/Form/FieldList.js
src/components/Form/FieldList.test.js
src/components/Form/Form.js
src/components/Form/Form.test.js
src/components/Form/FormElement.js
src/components/Form/FormElement.test.js

Simplified and improved form column layout. Default (3 columns, equal width) and `wide` flag (single full-width column) still work reasonably close to before.

Improve form layout system

---

src/components/Scope/Scope.test.js
src/components/Scope/index.js
src/components/Treeview/Treeview.test.js
src/components/Treeview/index.js
src/hooks/usePreviousModified.js
src/hooks/usePreviousModified.test.js

If the parent scope state was closed, the scope tree was not expanded to see the current scope.
Story: #26826

The current scope was not always visible when opening the selector.

---

docs/components.md
src/components/AppFrame/AppFrame.js
src/components/AppFrame/AppFrame.test.js
src/components/AppFrame/MenuItem.js
src/components/AppFrame/MenuItem.test.js
src/components/AppFrame/Sidebar.js
src/components/AppFrame/Sidebar.test.js

AppFrame's activeModules prop has changed, it is now an object instead of an array, module names are keys. Values should be boolean or objects of shape `{ type: ("confirm"|"warn"|"error")<string:optional>, message: <string|intlMessage:optional> }`. Boolean true shows a simple bright red marker at the module menu item. Setting `type` displays the marker in a color suiting the type of notification. Setting `message` will display a tooltip-like message with the activity notification. It is up to the application to add and remove mesaages as needed.

Feature: AB#36199 Add activity messages in module list

---

docs/components.md
src/components/AppFrame/Anchor.js
src/components/AppFrame/Anchor.test.js
src/components/AppFrame/Topbar.js
src/components/DropMenu/DropMenu.test.js
src/components/DropMenu/index.js
src/components/Navigation/Bar.js
src/components/Navigation/Bar.test.js

As the Anchor class that was the default anchor component for DropMenu was only used in AppFrame, I separated the two. The Anchor component was moved to AppFrame, while DropMenu will now add menus to its child components.

Separate DropMenu from Anchor

---

docs/actionsreducersselectors.md
package.json
src/buildStore.js
src/buildStore.test.js
src/components/AppFrame/AppFrame.test.js
src/components/AppFrame/Preferences.js
src/components/AppFrame/Preferences.test.js
src/components/Provision.test.js
src/reducers/localeFactory.js
src/reducers/localeFactory.test.js
src/selectors/locale.js
src/selectors/locale.test.js

Languages options in Preference panel should be limited to those three choices only down below as per product owner requirements. The request to fetch supported cultures has other purposes completely and should not be used in preferences.
- English
- Français
- Italiano
"locales" in package.json should be built this way so user may switch from one language to another.
```
"locales": [
{"language": "English", "cultureIso": "en-US"},
{"language": "Français", "cultureIso": "fr-CA"},
{"language": "Italiano", "cultureIso": "it-IT"}
]
```

Changed how languages options should be handled in preferences.

---

src/components/List/DataCell.js
src/components/List/DataCell.test.js

Story #37570
The react-intl FormattedNumber requires a 0 value to be passed in as a "0".
Corrected DataCell to do this conversion.

Corrected DataCell $Nan value to be $0.00

---

src/components/MaterialUI/Navigation/TabBar.js
src/components/MaterialUI/Navigation/TabBar.test.js
src/selectors/view.js
src/selectors/view.test.js
src/utils/urlHelper.js
src/utils/urlHelper.test.js

Add modification indication * on NEW entity tab
Show confirmation modal when New tab with modifications is closing
Remove edit mode for New tab when tab is closed
[AB#42239](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42239)

Modification indication for New entity tab

---

src/actions/view.js
src/components/Routing/SegmentPage.js
src/components/Routing/SegmentPage.test.js
src/reducers/view.js
src/reducers/view.test.js
src/selectors/view.js
src/selectors/view.test.js
src/utils/propertyHelper.js
src/utils/propertyHelper.test.js

[AB#43266](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43266)
- it is possibe to save error for model fields for  specific section so error can be displayed near the field
- when field change value - the error is cleared
- if section has any error, then it is higlighed like this (to be confirmed with designer)

Highlight sections with errors

---

src/components/Routing/SegmentPage.js
src/components/Routing/SegmentPage.test.js

Example of **static** usage:
```
segments: {
"/disabledSection": {
label: "Disabled section",
disabled: true,
},
"/hiddenSection": {
label: "Hidden section",
hide: true,
},
},
```
Example of **dynamic** usage:
```
segments: {
"/disabledSection": {
label: "Disabled section",
disabled: isCountryActiveSelector,
},
"/hiddenSection": {
label: "Hidden section",
hide: isCountryActiveSelector,
},
},
```
[AB#43629](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/43629)

Ability to Hide/Disable sections

---

.az.yml

Node version was updated to 15 since it uses npm 7.x which now installs peer deps automatically (that will save us from the issues when related packages adds some extra deps in new versions and our build getting failed after this).

Update .az.yml for Azure Pipelines

---

src/components/Routing/FullPage.js
src/components/Routing/FullPage.test.js
src/components/Routing/SegmentPage.js
src/components/Routing/SegmentPage.test.js

This modifications allows the entityId of a SegmentPage to be overriden
from module.js. This was made to allow pages without Ids (order
settings) or pages with a different route pattern (providers) to work with
the edition framework already in place (useEditState).
#25175

Allow the entityId of a SegmentPage to be overridden

---

src/utils/mapHelper.js
src/utils/mapHelper.test.js

This adds a custom transform method for mapHelper. Some model have
a property mapped to more than one UI fields. This modification allow a
different mapping for these fields.
#25175

Add custom mapping capabilities to mapHelper

---

src/components/MaterialUI/DataDisplay/Table.js
src/components/MaterialUI/DataDisplay/Table.test.js

Context variable will allow to use fields which not related explicitly to the table but, if they are changed we need table to be rerendered.

Add context property to table component

---

src/components/MaterialUI/Navigation/TabBar.js
src/components/MaterialUI/Navigation/TabBar.test.js

This PR will allow to remove validation results in cases like described in this bug.
https://dev.azure.com/orckestra001/OrckestraCommerce/_workitems/edit/44412/

Remove edit state if no modifications applied to the tab

---

src/utils/setTranslationWithFallback.js
src/utils/setTranslationWithFallback.test.js

For example when Display Name is absent for Custom Attributes, we need to Display Attribute Name for Input Label instead.

Ability to specify Fallback Value for Translations.

---

src/components/MaterialUI/Navigation/TabBar.js
src/components/MaterialUI/Navigation/TabBar.test.js

This fix isn't perfect because it wouldn't support multiple ids in params but..
It's still better than picking the first param that isn't "scope"

Support multi params path in closeTab pattern

---

src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.js
src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.test.js
src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.js
src/components/MaterialUI/DataDisplay/PredefinedElements/StepperModal.test.js
src/components/MaterialUI/DataDisplay/tableHelpers.js
src/components/MaterialUI/Inputs/Switch.js
src/components/MaterialUI/Inputs/SwitchProps.js
src/components/MaterialUI/Inputs/SwitchProps.test.js
src/components/MaterialUI/muiThemes.js
src/components/Scope/Scope.test.js
src/components/Scope/index.js

Allow Switch component wrapper to accept style overrides to allow customization from anywhere
Standardized the code used for the action buttons (create order, create customer, etc ..)

Switch component to allow style override

---

src/components/MaterialUI/DataDisplay/tableHelpers.js
src/components/MaterialUI/DataDisplay/tableHelpers.test.js

Standardized how custom builder are invoked from the table helper.
Story: #45617

Standardized how custom builder are invoked

---

src/components/MaterialUI/Feedback/loadingScreen.js
src/components/MaterialUI/Feedback/loadingScreen.test.js

Disable onMouseDown event on LoadingScreen component, as it causes strange text selections to occur on double/triple clicks.
Story ABC#45519

Disable onMouseDown event on LoadingScreen component

---

src/components/MaterialUI/DataDisplay/Modal.js
src/components/MaterialUI/DataDisplay/PredefinedElements/ActionModal.js
src/components/MaterialUI/DataDisplay/PredefinedElements/ActionModal.test.js
src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.js
src/components/MaterialUI/DataDisplay/PredefinedElements/ConfirmationModal.test.js

- Added a generic action modal component to support more than two buttons.
- Adjusted confimationModal to use the new one instead of being a breaking change.
Story: #43800

Added a generic action modal component to support more than two buttons.

---

src/components/MaterialUI/Inputs/Radio.js
src/components/MaterialUI/Inputs/Radio.test.js
src/components/MaterialUI/Inputs/RadioProps.js
src/components/MaterialUI/Inputs/RadioProps.test.js

This is used for radio groups that are created using values from the
backend like the fulfillment method types. Some customers have only one
fulfillment method type enabled and it needs to be selected when
creating a new order.
#46210

Allow radio group to only have one option

---

src/components/MaterialUI/DataDisplay/Table.js
src/components/MaterialUI/DataDisplay/Table.test.js
src/components/MaterialUI/Inputs/Checkbox.js
src/components/MaterialUI/Inputs/CheckboxProps.js
src/components/MaterialUI/Inputs/CheckboxProps.test.js
src/components/MaterialUI/muiThemes.js

+ Added props to allow the indeterminate state in the Checkbox wrapper component
+ Added props to accept basic onChange events for the Checkbox wrapper component
+ Added styling for the indeterminate state
+ Replaced Material UI Checkbox with the orc-shared version

Fix checkbox styles in Table

---

src/components/MaterialUI/Inputs/InputBase.js
src/components/MaterialUI/Inputs/InputBase.test.js

Correct Numeric input for FireFox, with onBlur
Story ABCD#46327

Correct Numeric input for FireFox, with onBlur

---

src/components/MaterialUI/Inputs/Select.js
src/components/MaterialUI/Inputs/Select.test.js
src/components/MaterialUI/muiThemes.js

+ Add some width to the left side content of the TimeLine
+ Added word-break to allow content wrapping for TimeLine content
+ Add styles for multiple levels Select options
+ Add way to parse the level passed from the Select options
+ Add a configurable base value for the indent amount in theme

TimeLine and Select fixes

---

src/components/MaterialUI/DataDisplay/SelectionList.js
src/components/MaterialUI/DataDisplay/SelectionList.test.js
src/components/MaterialUI/DataDisplay/TransferList.js

In TransferList, setChecked and onChange sometimes both cause re-renders
Sometimes, the onChange setState is called before the setChecked rendering finishes and react throws a warning "invalid setState during component rendering"
Calling onChange with useEffect fixes the problem

Add params to selection list

---

src/components/MaterialUI/DataDisplay/Badge.js
src/components/MaterialUI/DataDisplay/Badge.test.js
src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.js
src/components/MaterialUI/Inputs/PredefinedElements/SearchControl.test.js
src/components/MaterialUI/hocs/withDeferredPopper.js
src/components/MaterialUI/hocs/withDeferredPopper.test.js
src/components/Routing/SegmentPage.js
src/components/Routing/SegmentPage.test.js

Add ability to override styling for Badge and Popper components 
Prevent event bubbling when the Popper is the child of a Link <a>
Allow SearchControl to render without the Select component

Updates for Badge, Popper and SearchControl

---

src/actions/navigation.js
src/actions/navigation.test.js
src/components/MaterialUI/Navigation/TabBar.js
src/components/MaterialUI/Navigation/TabBar.test.js
src/components/Navigation/useNavigationState.js
src/components/Navigation/useNavigationState.test.js
src/components/Scope/useScopeConfirmationModalState.js
src/components/Scope/useScopeConfirmationModalState.test.js
src/reducers/navigation.js
src/reducers/navigation.test.js
src/selectors/navigation.js
src/selectors/navigation.test.js

- Invokes close tab handler when changing scope
- Invokes close tab handler when cancelling the edition of a new order
Story: #48283, #48233, #48204, #48030

Invokes close tab handler when changing scope

---

src/components/MaterialUI/DataDisplay/PredefinedElements/InformationItem.js
src/components/MaterialUI/DataDisplay/Table.js
src/components/MaterialUI/DataDisplay/Table.test.js
src/components/MaterialUI/DataDisplay/tableHelpers.js
src/components/MaterialUI/DataDisplay/tableHelpers.test.js
src/components/MaterialUI/hocs/withDeferredPopper.js

Tables:
Update width of Table cells with select input
- in header
- in content
Allow custom Row styling in Table
InformationItem:
Fix the layout of the label that has a warning icon
Fix label styling to remove extra margin-bottom for input Labels
Popper:
Add the property **placement** to the wrapped Popper component with default "bottom" value

Styling updates

---

src/components/MaterialUI/DataDisplay/SelectionList.js
src/components/MaterialUI/DataDisplay/SelectionList.test.js

- Allow SelectionList to reset on new list
- Reset selection if id does not exist
- 
Story [AB#48485](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/48485)

Allow SelectionList to reset on new list

---

package.json
src/actions/view.js
src/actions/view.test.js
src/hooks/useEditState.js
src/hooks/useEditState.test.js
src/hooks/useFullEntityEditState.js
src/hooks/useFullEntityEditState.test.js
src/reducers/view.js
src/reducers/view.test.js

- Resuming entity editing does not display modification indicators
- Run validations when required and when saving initial value in edit state
- Add ability to fully remove a portion of the edit state
Story: #46785

Resuming entity editing does not display modification indicators

---

src/components/MaterialUI/Navigation/TabBar.js

+ Fixed the case when  value = 0 and page.length = 1 was never called
+ removed the Math.max function to allow negative values in getNewIndex()
+ Add a condition to differentiate between 0 and false (false >= 0 is true)

Fix Tab navigation logic error

---

docs/hooks.md
src/actions/requestState.js
src/actions/requestState.test.js
src/buildStore.js
src/constants.js
src/hooks/useNotificationRequestState.js
src/hooks/useNotificationRequestState.test.js
src/hooks/useRequestState.js
src/hooks/useRequestState.test.js
src/reducers/requestStates.js
src/reducers/requestStates.test.js
src/selectors/requestStates.js
src/selectors/requestStates.test.js

This hook is used to simplify the handling of user message based on the
outcome of a request. For example you can use it to display a
notification after deleting an entity.

Add new useRequestState and useNotificationRequestState hooks

---

src/components/MaterialUI/ScopeSelector/TreeItem.js
src/components/MaterialUI/muiThemes.js

+ Fix the scope icons alignment when there are no expand or collapse icon in front
+ Added a line to fill the gap
to

Fix Scope TreeView alignment

---

src/components/MaterialUI/DataDisplay/Table.js
src/components/MaterialUI/Inputs/InputBase.js
src/components/MaterialUI/Inputs/InputBase.test.js

[AB#52079](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/52079)
Removed the tooltip text when an input is not of type "text"
Fixed table padding for the first element in the row

Remove tooltip on Input base other than text

---

src/actions/scopes.js
src/actions/scopes.test.js
src/components/ApplicationModuleLoader.js
src/components/ApplicationModuleLoader.test.js
src/reducers/settings.js
src/reducers/settings.test.js

- Scopes were not properly loaded for System modules
- It did not handle properly the use case where a module had no access to a scope tree
Story: [AB#54170](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/54170)  [AB#54173](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/54173)

Scopes were not properly loaded for System modules

---

src/components/MaterialUI/DataDisplay/SelectionList.js
src/components/MaterialUI/DataDisplay/SelectionList.test.js

#55248
Based on TransferList.js, the expected parameter name for the list on the left should be "left"

Rename object parameter to its expected value "left"

---

src/components/Culture.js
src/components/Culture.test.js
src/components/I18n.js
src/components/I18n.test.js
src/components/MaterialUI/Inputs/DatePicker.js
src/components/MaterialUI/Inputs/DatePicker.test.js
src/components/Provision.js
src/utils/localizationHelper.js
src/utils/localizationHelper.test.js

Use browser language to display date, time, first day of week, etc.
Texts translation will still be used on the user preferences.
Story: [AB#56888](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/56888)

Use browser language to display date, time, first day of week, etc.

---

src/components/MaterialUI/Inputs/InputBase.js
src/components/MaterialUI/Inputs/InputBaseProps.js
src/components/MaterialUI/Inputs/InputBaseProps.test.js

Add configurable timeoutDelay attribute that delay update of
editstate object that triggers a call when modified.
[AB#57779](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/57779)

Add timeout delay to prevent search Find call

---

src/components/MaterialUI/Inputs/InputBase.js

set the inputText to null after it updated the value so it does not override the next value
#58749

set the inputText to null after it updated the value
